"""empty message

Revision ID: 3d541ec31bb1
Revises: None
Create Date: 2015-10-07 11:40:52.366584

"""

# revision identifiers, used by Alembic.
revision = '3d541ec31bb1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('room', sa.String(length=120), nullable=False),
    sa.Column('week', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_name'), 'assignment', ['name'], unique=False)
    op.create_index(op.f('ix_assignment_room'), 'assignment', ['room'], unique=False)
    op.create_index(op.f('ix_assignment_week'), 'assignment', ['week'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_week'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_room'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_name'), table_name='assignment')
    op.drop_table('assignment')
    ### end Alembic commands ###
